### ISSUE TITLE
I can not do type in editor.php page

### ISSUE THREAD

**Issue by clh021** [simon-thorpe/editor#2]
Hello, thank you very much for the development of this powerful application software
I have to download and install directly via wget command
Not found in your description of them have other settings need to make
Then I successfully opened the editor.php in chrome browser
But I can not editing any files, I can not do input operation
Key did not respond words on the page, while other pages are normal.

this google translate maybe not friendly to read
now in chinese

您好，非常感谢您开发了这款强大的应用软件
我通过 wget 命令直接进行下载安装
没有在您的说明当中发现有其它需要进行的设置
然后我顺利的在 chrome 浏览器 中 打开了 editor.php 
但是我发现似乎不能编辑，我无法进行输入的操作
按键都没有反应，而在其它网页中是正常的。

**Comment by simon-thorpe** [comment]
Hi,

The editor does not allow you to type when the file you are editing does not have write permissions.
I just have added a commit that adds "[readonly]" to the page title if the file is not writable so make this more obvious.

If your webhost does not allow writing to files then you will need them to change the permissions for you. If you have FTP access you can do this yourself. Normally in a WordPress site only wp-content and a few other directories are set with write permissions. This unfortunately makes editing with editor.php pretty useless.

**Comment by clh021** [comment]
Oh, yes, thank you very much, I forgot about it, I'm sorry because such a simple thing to help your.

**Comment by clh021** [comment]
A small suggestion is that you can add in the next prompt readonly save and save and close the two buttons. Because I'm going to try looking for tips and input buttons when i can't type.

一个小小的建议是，您可以在 save 和 save and close 两个按钮旁边加上 File attribute readonly 的提示
因为我会在不能输入的时候直觉性的去尝试寻找提示和按钮

Finally, thank you again.
